# SwiftLint configuration file for AICollaborator

# Disabled rules
disabled_rules:
  - trailing_comma
  - vertical_parameter_alignment
  - opening_brace

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - last_where
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition

# Configure line length
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: false
  ignores_interpolated_strings: true

# Configure file length
file_length:
  warning: 500
  error: 700
  ignore_comment_only_lines: true

# Configure function body length
function_body_length:
  warning: 60
  error: 100

# Configure type body length
type_body_length:
  warning: 300
  error: 500

# Configure cyclomatic complexity
cyclomatic_complexity:
  warning: 15
  error: 25

# Identifier name configuration
identifier_name:
  min_length: 
    warning: 3
    error: 2
  excluded:
    - id
    - URL
    - pr
    - to
    - in
    - at
    - of
    - up
    - x
    - y
    - z

# Nesting configuration
nesting:
  type_level:
    warning: 3
    error: 5

# Reporter type
reporter: "xcode"

# Included paths
included:
  - Sources
  - Tests

# Excluded paths
excluded:
  - Carthage
  - Pods
  - .build
  - vendor
  - DerivedData
  - fastlane
  - "**/*.generated.swift"

# SwiftLint configuration for AICollaborator

# Disabled rules
disabled_rules:
  - todo # Allow TODOs for development

# Opt-in rules (enabled on top of default rules)
opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - vertical_parameter_alignment_on_call
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - unused_private_declaration

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 800

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

large_tuple:
  warning: 3
  error: 5
  
nesting:
  type_level:
    warning: 3
    error: 5
  function_level:
    warning: 4
    error: 6
    
cyclomatic_complexity:
  warning: 15
  error: 25

trailing_whitespace:
  ignores_empty_lines: true
  
identifier_name:
  min_length: 
    warning: 3
    error: 2
  excluded:
    - id
    - URL
    - url
    - URI
    - uri
    - as
    - at
    - by
    - or
    - to
    - in
    - if
    - of
    - on
    - up
    - i
    - j
    - k
    - x
    - y
    - z

# Paths to include/exclude when running SwiftLint
included:
  - Sources
  - Tests
  
excluded:
  - .build
  - Dependencies
  - Carthage
  - Pods
  - DerivedData
  - "**/*.generated.swift"
  - "fastlane/**/*"
  - "*/Frameworks/*"
  - "*/Resources/*"

# Format of reporter to use when linting
reporter: "xcode"

