name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: '5.9'
    
    - name: Show Swift version
      run: swift --version

    - name: Show Xcode version
      run: xcodebuild -version
      
    - name: Show SDK path
      run: xcrun --show-sdk-path
      
    - name: Build
      run: |
        sdk_path=$(xcrun --show-sdk-path)
        swift build -v -Xswiftc "-sdk" -Xswiftc "$sdk_path" -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.15"
      
    - name: Run tests
      run: |
        sdk_path=$(xcrun --show-sdk-path)
        swift test -v -Xswiftc "-sdk" -Xswiftc "$sdk_path" -Xswiftc "-target" -Xswiftc "x86_64-apple-macosx10.15"
  
  swiftlint:
    name: SwiftLint
    runs-on: macos-13
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: |
        brew install swiftlint
        swiftlint --version
    
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging --config .swiftlint.yml
      
    # Alternative SwiftLint action if the above fails
    - name: SwiftLint (alternative)
      if: failure()
      uses: norio-nomura/action-swiftlint@3.2.1
      with:
        args: --strict

